services:
  postgres:
    image: postgres:17
    container_name: PostgresLaravel
    restart: always
    environment:
      POSTGRES_DB: Youvento
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdminLaravel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mvc.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "8088:80"
    networks:
      - laravel_network

  php:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./project:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - laravel_network
# mysql:
#   image: mysql
#   container_name: db_mysql

# db:
#   image: mariadb:10.11
#   restart: always
#   environment:
#     MYSQL_ROOT_PASSWORD: notSecureChangeMe

# phpmyadmin:
#   image: phpmyadmin
#   restart: always
#   ports:
#     - 8080:80
#   environment:
#     - PMA_ARBITRARY=1

volumes:
  postgres_data:

networks:
  laravel_network:
